import { CmsCollection, CmsField } from "netlify-cms-core";
import { getPreviewPath } from "../preview/paths";

import { createPageBuilder } from "./page-builder";

const createGlobalFields = (): CmsField[] => [
  {
    name: "title",
    widget: "string",
    label: "Title",
    required: true,
  },
  {
    name: "date",
    widget: "datetime",
    label: "Publish Date",
    date_format: "ddd D MMM YYYY",
    time_format: "h:mm:ss a Z",
    format: "YYYY-MM-DD HH:mm:ss Z",
    picker_utc: false,
    required: false,
    // default: undefined = current time
  },
  {
    name: "expiry",
    widget: "datetime",
    label: "Expiry Date",
    date_format: "ddd D MMM YYYY",
    time_format: "h:mm:ss a Z",
    format: "YYYY-MM-DD HH:mm:ss Z",
    picker_utc: false,
    required: false,
    default: "",
  },
  {
    name: "disabled",
    widget: "boolean",
    label: "Disabled",
    required: false,
    default: false,
  },
];

export const cmsCollections: CmsCollection[] = [
  {
    name: "singlePages",
    label: "Single Pages",
    label_singular: "Single Page",
    files: [
      {
        name: "home",
        label: "Home",
        file: "cms-content/home.md",
        preview_path: getPreviewPath((p) => p),
        fields: [
          createPageBuilder(),
          {
            widget: "relation",
            collection: "news",
            name: "newsItems",
            label: "News Items",
            multiple: true,
            required: false,
            search_fields: ["{{slug}}", "title", "author", "intro", "body"],
            value_field: "RelationTo:news ItemSlug:{{slug}}",
            display_fields: ["{{slug}} {{title}}"],
          },
          {
            widget: "relation",
            collection: "pages",
            name: "pageRelation",
            label: "Page Relation",
            required: false,
            search_fields: [
              "{{slug}}",
              "title",
              "PAGEBUILDER.*",
              "PAGEBUILDER.*.markdown",
              "PAGEBUILDER.*.heading",
              "PAGEBUILDER.*.button.text",
            ],
            value_field: "RelationTo:pages ItemSlug:{{slug}}",
            display_fields: ["{{slug}} {{title}}"],
          },
        ],
      },
      {
        name: "newsIndex",
        label: "News [index]",
        file: "cms-content/news.md",
        preview_path: getPreviewPath((p) => p.news),
        fields: [createPageBuilder()],
      },
    ],
  },
  {
    name: "pages",
    label: "Pages",
    label_singular: "Page",
    folder: "cms-content/pages",
    preview_path: getPreviewPath((p) => p._slug("{{slug}}")),
    create: true,
    fields: [
      ...createGlobalFields(),
      createPageBuilder(),
      {
        widget: "relation",
        collection: "news",
        name: "newsItems",
        label: "News Items",
        multiple: true,
        required: false,
        search_fields: ["{{slug}}", "title", "author", "intro", "body"],
        value_field: "RelationTo:news ItemSlug:{{slug}}",
        display_fields: ["{{slug}} {{title}}"],
      },
      {
        widget: "relation",
        collection: "pages",
        name: "pageRelation",
        label: "Page Relation",
        required: false,
        search_fields: [
          "{{slug}}",
          "title",
          "PAGEBUILDER.*",
          "PAGEBUILDER.*.markdown",
          "PAGEBUILDER.*.heading",
          "PAGEBUILDER.*.button.text",
        ],
        value_field: "RelationTo:pages ItemSlug:{{slug}}",
        display_fields: ["{{slug}} {{title}}"],
      },
    ],
  },
  {
    name: "news",
    label: "News Posts",
    label_singular: "Post",
    folder: "cms-content/news",
    create: true,
    slug: "{{slug}}",
    preview_path: getPreviewPath((p) => p.news._slug("{{slug}}")),
    fields: [
      ...createGlobalFields(),
      {
        name: "author",
        widget: "string",
        label: "Author",
      },
      {
        name: "thumbnail",
        widget: "image",
        label: "Featured Image",
      },
      {
        name: "intro",
        widget: "text",
        label: "Intro",
      },
      {
        name: "body",
        widget: "markdown",
        label: "Body",
      },
      {
        widget: "relation",
        collection: "news",
        name: "newsItems",
        label: "News Items",
        multiple: true,
        required: false,
        search_fields: ["{{slug}}", "title", "author", "intro", "body"],
        value_field: "RelationTo:news ItemSlug:{{slug}}",
        display_fields: ["{{slug}} {{title}}"],
      },
      {
        widget: "relation",
        collection: "pages",
        name: "pageRelation",
        label: "Page Relation",
        required: false,
        search_fields: [
          "{{slug}}",
          "title",
          "PAGEBUILDER.*",
          "PAGEBUILDER.*.markdown",
          "PAGEBUILDER.*.heading",
          "PAGEBUILDER.*.button.text",
        ],
        value_field: "RelationTo:pages ItemSlug:{{slug}}",
        display_fields: ["{{slug}} {{title}}"],
      },
      {
        widget: "relation",
        collection: "singlePages",
        name: "singlePageRelation",
        label: "Single Page Relation",
        required: false,
        search_fields: [
          "{{slug}}",
          "PAGEBUILDER.*",
          "PAGEBUILDER.*.markdown",
          "PAGEBUILDER.*.heading",
          "PAGEBUILDER.*.button.text",
        ],
        value_field: "RelationTo:singlePages ItemSlug:{{slug}}",
        display_fields: ["{{slug}} {{title}}"],
      },
    ],
  },
];
